WebCalender/Controllers/ApiEventCategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.JSInterop.Implementation;
using Newtonsoft.Json;
using System.Security.Claims;
using System.Text;
using WebCalender.Models;

namespace WebCalender.Controllers
{
    
    [Authorize(Roles = "Admin")]
    public class ApiEventCategoryController : Controller
    {
        
        public IActionResult Index()
        {
            return View();
        }

        public ViewResult AddEventCategories() => View();

      
        [HttpPost]
        public async Task<IActionResult> AddEventCategories(CalendarEventCategory calenderEventCategory)
        {
            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(calenderEventCategory), Encoding.UTF8, "application/json");
                using (var response = await httpClient.PostAsync("http://apitest.lunarit.com.np/api/apiEventCategory/addeventcategory", content))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                }
            }
            return Redirect("GetEventCategories");
        }

        
        public async Task<IActionResult> GetEventCategories()
        {
            List<CalendarEventCategory>? eventList = new List<CalendarEventCategory>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("http://apitest.lunarit.com.np/api/apiEventCategory/geteventcategories"))
                {
                    string? apiResponse = await response.Content.ReadAsStringAsync();
                    eventList = JsonConvert.DeserializeObject<List<CalendarEventCategory>>(apiResponse);
                }
            }
            return View(eventList);
        }


        
        public async Task<IActionResult> UpdateEventCategory(int id)
        {
            List<CalendarEventCategory> eventList = new List<CalendarEventCategory>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("http://apitest.lunarit.com.np/api/apiEventCategory/geteventcategories"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    eventList = JsonConvert.DeserializeObject<List<CalendarEventCategory>>(apiResponse);
                }
            }
            var list = eventList?.Where(x => x.EventId == id).FirstOrDefault();
            return View(list);
        }

        

        [HttpPost]
        public async Task<IActionResult> UpdateEventCategory(CalendarEventCategory calendarEventCategory)
        {
            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(calendarEventCategory), Encoding.UTF8, "application/json");

                using (var response = await httpClient.PutAsync("http://apitest.lunarit.com.np/api/apiEventCategory/updateeventcategory", content))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                }
            }
            return RedirectToAction("GetEventCategories");
        }

        [HttpGet]
        public async Task<IActionResult> DeleteEventCategory(int id)
        {
            List<CalendarEventCategory> eventList = new List<CalendarEventCategory>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("http://apitest.lunarit.com.np/api/apiEventCategory/geteventcategories"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    eventList = JsonConvert.DeserializeObject<List<CalendarEventCategory>>(apiResponse);
                }
            }
            var list = eventList?.Where(x => x.EventId == id).FirstOrDefault();
            return View(list);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.DeleteAsync("http://apitest.lunarit.com.np/api/apiEventCategory/deleteeventcategory/" + id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    
                }
            }
            return RedirectToAction("GetEventCategories");
        }
    }
}

WebCalender/Views/ApiEventCategory/AddEventCategories.cshtml
@model WebCalender.Models.CalendarEventCategory

<h4>CalendarEventCategory</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="ApiEventCategory" asp-action="AddEventCategories" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
            <div class="form-group">
                <label asp-for="EventName" class="control-label"></label>
                <input asp-for="EventName" class="form-control" />
                <span asp-validation-for="EventName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventColor" class="control-label"></label>
                <input asp-for="EventColor" class="form-control" />
                <span asp-validation-for="EventColor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RemarkPosition" class="control-label"></label>
                <select asp-for="RemarkPosition" class="form-control">
                    <option value="Footer">Footer</option>
                    <option value="InPlace">InPlace</option>
                    <option value="None">None</option>
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Add" class="btn btn-primary mt-2" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="GetEventCategories">Back to List</a>
</div>


@if (Model != null)
{
    <h2>Reservation</h2>
    <table class="table table-sm table-striped table-bordered m-2">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Start Location</th>
                <th>End Location</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Model.EventId</td>
                <td>@Model.EventName</td>
                <td>@Model.EventColor</td>
                <td>@Model.RemarkPosition</td>
            </tr>
        </tbody>
    </table>
}

WebCalender/Views/ApiEventCategory/DeleteEventCategory.cshtml
@model WebCalender.Models.CalendarEventCategory

@{
    ViewData["Title"] = "DeleteEventCategory";
}

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CalendarEventCategory</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventColor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventColor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RemarkPosition)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RemarkPosition)
        </dd>
    </dl>
    <form asp-action="Delete" method="post">
        <input type="hidden" value="@Model.EventId" name="id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="GetEventCategories">Back to List</a>
    </form>
</div>

WebCalender/Views/ApiEventCategory/GetEventCategories.cshtml
@model IEnumerable<WebCalender.Models.CalendarEventCategory>

@{
    ViewData["Title"] = "Read";
}

<h1>Your Events are shown below:-</h1>

<p>
    <a class="btn btn-primary" asp-action="AddEventCategories">Create New</a>
</p>
<div class="table-responsive readEvent">
<table class="table table-responsive table-bordered border-secondary table-striped table-hover">
    <thead>
        <tr>
            <th>
                S.N.
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EventName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EventColor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RemarkPosition)
            </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>

        @{
           int count = 1;
        }
        @foreach (var item in Model)
            {
                <tr>
                <td>
                    @count
                </td>
                <td>
                    @item.EventName
                </td>
                <td>
                    @item.EventColor
                </td>
                <td>
                    @item.RemarkPosition
                </td>
                <td>
                    <a class="btn btn-outline-primary" asp-action="UpdateEventCategory" asp-controller="ApiEventCategory" asp-route-id="@item.EventId">Edit</a>
                    <a asp-action="Delete" asp-controller="ApiEventCategory" asp-route-id="@item.EventId" class="btn btn-outline-danger" data-ajax="true" data-ajax-method="post" data-ajax-confirm="Are you sure?" data-ajax-complete="deletePage">Delete</a>

                </td>
            </tr>
            count++;
        }
    </tbody>
</table>
</div>


<script>
    $(document).ready(function () {
        postEvent = function (xhr) {
            alert("Event Updated Succeffuly");
            $('.btn-close').click();
            location.reload();
        }
        deletePage = function (xhr) {
            location.reload();
        }
    });
</script>

WebCalender/Views/ApiEventCategory/UpdateEventCategory.cshtml
@model WebCalender.Models.CalendarEventCategory

@{
    ViewData["Title"] = "UpdateEventCategory";
}

<h1>UpdateEventCategory</h1>

<h4>CalendarEventCategory</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="UpdateEventCategory" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EventId" class="control-label"></label>
                <input asp-for="EventId" class="form-control" readonly/>
                <span asp-validation-for="EventId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventName" class="control-label"></label>
                <input asp-for="EventName" class="form-control" />
                <span asp-validation-for="EventName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventColor" class="control-label"></label>
                <input asp-for="EventColor" class="form-control" />
                <span asp-validation-for="EventColor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RemarkPosition" class="control-label"></label>
                <select asp-for="RemarkPosition" class="form-control">
                    <option value="Footer">Footer</option>
                    <option value="InPlace">InPlace</option>
                    <option value="None">None</option>
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary mt-2" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="GetEventCategories">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}