WebCalender/Controllers/ApiEventDateController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Metadata;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.JSInterop.Implementation;
using Newtonsoft.Json;
using System.Text;
using WebCalender.Models;

namespace WebCalender.Controllers
{
    public class ApiEventDateController : Controller
    {
        //HttpGet to create a new event for the day,
        //Param is used to get the date
        //API is used to get the list of events
        public async Task<IActionResult> Index(string param)
        {
            List<CalendarEventCategory>? events = new List<CalendarEventCategory>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("http://apitest.lunarit.com.np/api/apiEventCategory/geteventcategories"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    events = JsonConvert.DeserializeObject<List<CalendarEventCategory>>(apiResponse);
                }
            }
            var elist=new SelectList(events, nameof(CalendarEventCategory.EventName), nameof(CalendarEventCategory.EventName));          
            ViewBag.eventList=elist;

            CalendarEventDate date = new CalendarEventDate
            {
                NepaliDate = param
            };
            return PartialView(date);
        }

        //Update function for HttpGet
        //All neccessary objects are obtained through out the function
        [HttpGet]
        public async Task<IActionResult> Update(string param)
        {
            DateTime date = DateTime.ParseExact(param, "yyyy-M-d", null);
            int month = date.Month;

            List<CalendarEventCategory>? eventCategory = new List<CalendarEventCategory>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("http://apitest.lunarit.com.np/api/apiEventCategory/geteventcategories"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    eventCategory = JsonConvert.DeserializeObject<List<CalendarEventCategory>>(apiResponse);
                }
            }
            var elist = new SelectList(eventCategory, nameof(CalendarEventCategory.EventName), nameof(CalendarEventCategory.EventName));
            ViewBag.eventList = elist;


            List<CalendarEventDate>? events = new List<CalendarEventDate>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("http://apitest.lunarit.com.np/api/apiEventDate/GetEventDayList/2080/" + month))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    events = JsonConvert.DeserializeObject<List<CalendarEventDate>>(apiResponse);
                }
            }
            var list = events?.Where(x => x.NepaliDate == param).FirstOrDefault();
            return PartialView(list);
        }

        //it is used to update the date event using the httpPost method
        [HttpPost]
        public async Task<IActionResult> Update(CalendarEventDate calendarEventDate)
        {
            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(calendarEventDate), Encoding.UTF8, "application/json");
                using (var response = await httpClient.PostAsync("http://apitest.lunarit.com.np/api/apiEventDate/AddCalendarEventDate", content))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                }
            }
            return RedirectToAction("Index", "Home");
        }

        //this method is to add a new event for the date through the post method
        [HttpPost]
        public async Task<IActionResult> Index(CalendarEventDate calendarEventDate)
        {
                using (var httpClient = new HttpClient())
                {
                    StringContent content = new StringContent(JsonConvert.SerializeObject(calendarEventDate), Encoding.UTF8, "application/json");
                    using (var response = await httpClient.PostAsync("http://apitest.lunarit.com.np/api/apiEventDate/AddCalendarEventDate", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                    }
                }
             return RedirectToAction("Index","Home");
        }


        //Admin can delete the event through the post method
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.DeleteAsync("http://apitest.lunarit.com.np/api/apiEventDate/DeleteCalendarEventDate/" + id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                }
            }
            return RedirectToAction("Index","Home");
        }
    }
}

WebCalender/Views/ApiEventDate/Index.cshtml
@model CalendarEventDate

@{
    ViewData["Title"] = "Add Event Date";
}

<form asp-action="Index" asp-controller="ApiEventDate" method="post" data-ajax="true" data-ajax-method="post" data-ajax-complete="postEvent">
    `       <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="staticBackdropLabel">Add Event for the Day</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="NepaliDate" class="form-control" />
                <span asp-validation-for="NepaliDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventName" class="control-label"></label>
                <select asp-items="@ViewBag.EventList" asp-for="EventName" class="form-control"></select>
                <span asp-validation-for="EventName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventDescription" class="control-label"></label>
                <input asp-for="EventDescription" class="form-control" />
                <span asp-validation-for="EventDescription" class="text-danger"></span>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
           
                <input type="submit" value="Create" class="btn btn-primary" />
            
            
        </div>
    </div>
</form>

<script>
    $(document).ready(function () {
        postEvent = function (xhr) {
            alert("Event Added Succeffuly");
            $('.btn-close').click();
            location.reload();
        }
    });
</script>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

WebCalender/Views/ApiEventDate/Update.cshtml
@using System.Security.Claims;
@model CalendarEventDate

@{
    ViewData["Title"] = "Update Event Date";
}

<form asp-action="Update" asp-controller="ApiEventDate" method="post" data-ajax="true" data-ajax-method="post"  data-ajax-complete="postEvent">
`       <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Update Event for the Day</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DateId" class="control-label"></label>
                <input asp-for="DateId" class="form-control" readonly />
                <span asp-validation-for="DateId" class="text-danger"></span>
            </div>

                <div class="form-group">
                <label asp-for="NepaliDate" class="control-label"></label>
                    <input asp-for="NepaliDate" class="form-control" readonly/>
                    <span asp-validation-for="NepaliDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="EventName" class="control-label"></label>
                <select asp-items="@ViewBag.eventList" asp-for="EventName" class="form-control"></select>
                    <span asp-validation-for="EventName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="EventDescription" class="control-label"></label>
                    <input asp-for="EventDescription" class="form-control" />
                    <span asp-validation-for="EventDescription" class="text-danger"></span>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                @if (@User.FindFirst(ClaimTypes.Role)?.Value == "Admin"){
                <input type="submit" value="Update" class="btn btn-primary" />
                <a asp-action="Delete" asp-controller="ApiEventDate" asp-route-id="@Model.DateId" class="btn btn-danger" method="post" data-ajax="true" data-ajax-method="post" data-ajax-confirm="Are you sure?" data-ajax-complete="deletePage">Delete</a>
                }
            
            </div>
        </div>
</form>


<script>
    $(document).ready(function(){       
        postEvent = function (xhr) {
            alert("Event Updated Succeffuly");
            $('.btn-close').click();
            location.reload();
        }
        deletePage = function (xhr) {
            $('.btn-close')[0].click();
            location.reload();
        }
    });
</script>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}